---
- name: Install prerequisites
  apt:
    name: [curl]
    state: present
    update_cache: yes

- name: Fetch k3s token from server
  slurp:
    src: /tmp/k3s_token
  delegate_to: "{{ groups['k3s_control'][0] }}"
  register: token_raw

- name: Decode token
  set_fact:
    k3s_token: "{{ token_raw.content | b64decode }}"

- name: Install k3s agent and join server
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL="https://{{ hostvars[groups['k3s_control'][0]].ansible_host }}:6443" K3S_TOKEN="{{ k3s_token }}" sh -s -
  args:
    creates: /usr/local/bin/k3s
