---
- name: Install prerequisites
  apt:
    name: [curl]
    state: present
    update_cache: yes

- name: Wait for k3s token to appear on control node
  delegate_to: "{{ groups['k3s_control'][0] }}"
  wait_for:
    path: /tmp/k3s_token
    state: present
    timeout: 120

- name: Fetch k3s token from control and decode
  delegate_to: "{{ groups['k3s_control'][0] }}"
  slurp:
    src: /tmp/k3s_token
  register: token_raw


- name: Decode token and trim
  set_fact:
    k3s_token: "{{ (token_raw.content | b64decode).strip() }}"

- name: Install k3s agent and join server
  shell: |
    if [ ! -x /usr/local/bin/k3s ]; then
      curl -sfL https://get.k3s.io | K3S_URL="https://{{ hostvars[groups['k3s_control'][0]].ansible_host }}:6443" K3S_TOKEN="{{ k3s_token }}" sh -s -
    fi
  args:
    creates: /usr/local/bin/k3s
