apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: taskapp
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
